# Generated by Django 5.2.4 on 2025-07-07 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ad")),
                ("last_name", models.CharField(max_length=100, verbose_name="Soyad")),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Doğum Tarihi"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Erkek"), ("F", "Kadın"), ("O", "Diğer")],
                        max_length=10,
                        null=True,
                        verbose_name="Cinsiyet",
                    ),
                ),
                (
                    "tc_kimlik_no",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        unique=True,
                        verbose_name="TC Kimlik Numarası",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Telefon Numarası"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-posta"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Adres"),
                ),
                (
                    "medical_history",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tıbbi Geçmiş"
                    ),
                ),
                (
                    "allergies",
                    models.TextField(blank=True, null=True, verbose_name="Alerjiler"),
                ),
                (
                    "current_medications",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mevcut İlaçlar"
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Kayıt Tarihi"
                    ),
                ),
                (
                    "last_notification_date_45",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son 45 Gün Bildirim Tarihi"
                    ),
                ),
                (
                    "last_notification_date_60",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son 60 Gün Bildirim Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hasta",
                "verbose_name_plural": "Hastalar",
                "ordering": ["-registration_date"],
            },
        ),
    ]
