# Generated by Django 5.2.4 on 2025-07-07 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="last_notification_date_10",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Son 10 Dakika Bildirim Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="registration_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Kayıt Tarihi"
            ),
        ),
    ]
